### ISSUE TITLE
Port to CoreCLR

### ISSUE THREAD

**Issue by TheRealPiotrP** [viagogo/HalKit#17] opened 2016-04-08 10:33 UTC
Would folks be open to a CoreCLR port? It would be nice to have HalKit available for .NET developers working on Linux, Mac, etc.

**Comment by akilb** [comment] 2016-04-09 07:04
@piotrpMSFT definitely. We'll get on this ourselves soon hopefully but feel free to send a pull request if you want

**Comment by piotrpMSFT** [comment] 2016-04-12 20:43
I'm working on a port in  my spare cycles. It's getting pretty close already. I'll push to my fork so we can chat about it once it's building.

**Comment by piotrpMSFT** [comment] 2016-04-12 20:49
By the way, I'm seeing just one test failure:
    HalKit.Tests.Http.HttpClientFactoryTests+TheConstructor.ShouldNotSetTheClientHandlerAutomaticDecompressionToNone_WhenItDoesntSupportAutoDecompression [FAIL]
      Assert.Equal() Failure
      Expected: None
      Actual:   GZip, Deflate
      Stack Trace:
           at HalKit.Tests.Http.HttpClientFactoryTests.TheConstructor.ShouldNotSetTheClientHandlerAutomaticDecompressionToNone_WhenItDoesntSupportAutoDecompression()


This doesn't seem like it would be related to what I'm doing. Is it a known issue?

**Comment by akilb** [comment] 2016-04-12 21:11
@piotrpMSFT ok great. Looking forward to the pull request then.

I'm not seeing any failures for that test locally or in the [CI build](https://ci.appveyor.com/project/viagogo/halkit/branch/master). Maybe there's some issue in the CoreCLR version of System.Net.Http?

**Comment by piotrpMSFT** [comment] 2016-04-12 21:18
I actually think the issue is in the Moq port.

**Comment by joaope** [comment] 2016-07-22 01:18
I just saw this issue, right after created #19 for exactly this.

Btw, @piotrpMSFT test is failing because HttpClientHandler.DecompressionMethod default values changed on new corefx. Relevant information on the same PR.

**Comment by piotrpMSFT** [comment] 2016-07-22 05:38
Yea, I looked that up after writing to this issue and fixed in a PR that is still looking for free time :)

**Closed** 2018-09-05 16:15 UTC
Labels: enhancement, help wanted
